name: Enviar archivo COES por correo

on:
  workflow_dispatch:  # ejecutable manualmente desde GitHub

jobs:
  enviar_despacho:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Clonar el repositorio
        uses: actions/checkout@v3

      - name: ğŸ Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: ğŸ“¦ Instalar dependencias
        run: pip install requests

      - name: ğŸ“„ Mostrar contenido del script
        run: cat scraping.py

      - name: ğŸš€ Ejecutar script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GMAIL_TO: ${{ secrets.GMAIL_TO }}
        run: python scraping.py
